apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prometheus.mydavidcloud.xyz
      secretName: prometheus-tls
  rules:
    - host: prometheus.mydavidcloud.xyz  # Replace with your desired domain for Prometheus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus  # Your existing Prometheus service name
                port:
                  number: 9090  # Port for Prometheus