name: Python App on Azure Kubernetes Service

on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths-ignore: 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
    terraform_infrastructure:
        runs-on: ubuntu-latest
        steps:
            - name: Repository Checkout
              uses: actions/checkout@v4
            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "4.0.1"
            - name: Terraform Init
              run: terraform init -backend-config="${{ secrets.AZURE_CREDENTIALS }}"
            - name: Terraform Plan
              run: |
                terraform plan | tee infraplan
            - name: Teraform Apply
              run: terraform apply "infraplan"