apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  replicas: 4 #10
  selector:
    matchLabels:
      app: flask-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-pod
        image: rigaacr.azurecr.io/flaskapp:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 128Mi
            cpu: "0.1"
        securityContext:
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - CHOWN
          allowPrivilegeEscalation: false
          runAsUser: 1001
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-secrets"
        # env:
        # - name: SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-secret
        #       key: SECRET_KEY
        # - name: DJANGO_ALLOWED_HOSTS
        #   valueFrom:
        #     configMapKeyRef:
        #       name: django-config
        #       key: ALLOWED_HOSTS
        # - name: ALLOWED_HOSTS
        #   value: '["48.209.176.167"]'
