apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-flask-hpa
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-flask-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50