apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:                      # Define Kubernetes Secret from Key Vault
    - secretName: my-secret
      type: Opaque
      data:
        - key: SECRET_KEY             # Key in Kubernetes Secret
          objectName: SECRET-KEY       # Name of the secret in Azure Key Vault
  parameters:
    usePodIdentity: "false"            # Keep false as you're not using Pod Identity
    useVMManagedIdentity: "true"       # True for system-assigned identity
    userAssignedIdentityID: d20e6dbf-4389-423a-9f8f-a296cf4c29b7 #769ddd15-ef0d-4cfa-a68c-95d6e708a6f4
    keyvaultName: myrigamortuskeyvault    # Name of your Key Vault
    objects: |
      array:
        - |
          objectName: SECRET-KEY      # Name of the secret in Key Vault
          objectType: secret          # The type of object (secret, key, or cert)
    tenantId: 215b7ce2-5263-4593-a622-da030405d151
    syncSecret: "true"
